### ISSUE TITLE
Compatibility with Graves

### ISSUE THREAD

**Issue by TylorTurner** [derfurkan/OfflinePlayers#15]
I added you on Discord to ask if there was any compatibility, I don't know why you added me then blocked me but I thought I would try again since ego probably does not matter over a Minecraft plugin. 

I think it would be a really cool addition for graves of any kind to activate after the player gets killed while offline. This would allow them time to get on and still be able to retrieve their loot.

this is the graves plugin
https://www.spigotmc.org/resources/graves.74208/
They have new Dev builds on Discord.

**Comment by derfurkan** [comment]
Hi, First of all I have blocked you on Discord because in my eyes normal people greet each other first and initiate the topic. I found it disrespectful to just start the topic directly without first introducing the topic and saying exactly what it is about before you describe your problem. As I provide my support in my free time, I don't see the point in replying to something like that. 

OfflinePlayers will not have support with the Graves plugin. However, this should be relatively easy to create yourself as OfflinePlayers has an API that contains an OfflinePlayerDeathEvent. If this event is called, you can spawn the gravestones yourself if the Graves plugin also has an API for this.

**Comment by TylorTurner** [comment]
Do you think it would be a bad idea to for the players to have a last chance to regain their loot with a grave system? What if a player lags out and everything is gone. A grave system with a timer might be a huge improvement to this plugin, which is the best idea I have seen yet. MC should have always been based around this. 

Also with Multiverse Inventories if a player just logs out in another world they save their INV, or you would think but it just deletes their survival INV anyways if they die. It sure would be cool to set a world to force spawn the players in if they log out in specific MV worlds avoiding players hiding or glitching their loot.

Additionally a health system to the OfflinePlayer would be nice making killing them a bit longer giving an additional few seconds for the player to come back, could be lag or anything this might help the player recover.

**Comment by derfurkan** [comment]
> Do you think it would be a bad idea to for the players to have a last chance to regain their loot with a grave system? What if a player lags out and everything is gone. A grave system with a timer might be a huge improvement to this plugin allowing the player and attacker a timer to fight over the loot. This plugin idea Is the best I have seen yet. MC should have always been based around this.
> 
> Also with Multiverse Inventories if a player just logs out in another world they save their INV, or you would think but it just deletes their survival INV anyways if they die. It sure would be cool to set a world to force spawn the players in if they log out in specific MV worlds avoiding players hiding or glitching their loot.
> 
> Additionally a health system to the OfflinePlayer would be nice making killing them a bit longer giving an additional few seconds for the player to come back, could be lag or anything this might help the player recover.
> 
> Another idea I use ReviveMe and it allows you to pick up players, it would be really cool to pick up your teammates with Towny or any other Team plugin and move them to keep them safe if you are getting raided etc.

OfflinePlayers is not supposed to be a big plugin. The idea behind the plugin is simply to keep the player on the server while he is actually offline. That is the basic idea behind the whole thing and it should stay that way. Everything you mentioned could be implemented yourself with the API that the plugin provides. In addition, the source code of the plugin is available for free on GitHub where anyone can change it and program their own versions of the plugin. The whole thing is just a side project that I created in my spare time out of boredom and I don't want to work on it much anymore.

**Comment by TylorTurner** [comment]
Would you be open for a payment for the work? If you don't have a passion for this plugin I understand that but this is literally the best idea a survival can have. I really hope you consider working on it more. Let me know a cost please.

**Comment by TylorTurner** [comment]
Also the players body does not remain after a server restart?
