### ISSUE TITLE
World Whitelist/Blacklist

### ISSUE THREAD

**Issue by Chris6ix** [derfurkan/OfflinePlayers#2]
Hey, I really like the idea of your plugin and I would like to use it on my server, however, it is sadly missing a quite important feature.

That feature is the ability to only have the plugin run in specific worlds.

This can be done either via a world whitelist or a world blacklist. Both are fine, so I guess you can choose which one you like more :)

I (And I would say a lot of other people) would really appreciate if you could add one of them.

Cheers,
Chris6ix

**Comment by derfurkan** [comment]
Hey!
Yeah i can implement that! 
I think i also add an permission function where you can then specify which player should get a clone or not.
I will post the update here if its out! Shouldn't take long

**Comment by Chris6ix** [comment]
Thanks for the super fast response :)
Sounds great!

**Comment by derfurkan** [comment]
So i've updated the plugin to version 1.6 where the configuration contains a _worldBlacklist_ section and a _permissions_ section.
But i haven't tested it fully yet so bugs can occur.

**Also for that update to work you may need to regenerate your config.yml file so the new sections will be added.**

https://www.spigotmc.org/resources/offlineplayers-prevent-players-from-going-offline.104985/updates

**Comment by Chris6ix** [comment]
Thank you for adding this so quickly :)
I will give it a try when I have some time and report any issues.
