### ISSUE TITLE
Is it possible to prevent spectator players from becoming clones?

### ISSUE THREAD

**Issue by Lead-Lord** [derfurkan/OfflinePlayers#4]
I do not want clones to appear when a player in spectator mode disconnects. Can you consider creating a disable option in the config?

**Comment by derfurkan** [comment]
Hi! I just updated the plugin to version 1.7
In this version you will have a 'gamemodeBlacklist' in your config.yml file.

**You can download it [here](https://www.spigotmc.org/resources/offlineplayers-prevent-players-from-going-offline.104985/updates)**

**Thank you for suggesting this feature and have a great day!**
