### ISSUE TITLE
[Feature] clone attacked

### ISSUE THREAD

**Issue by Lead-Lord** [derfurkan/OfflinePlayers#7]
How about adding the ability for clones to be attacked by monsters just like real players? It's my personal opinion, but I think it's pretty good!

**Comment by derfurkan** [comment]
### Hey i liked the feature so i implemented it into the newest version.
You can enable and disable it by the `cloneCanProvoke` config value.

**Here is the link to the update: https://www.spigotmc.org/resources/offlineplayers-never-let-players-disappear.104985/update?update=505104**

**Comment by Lead-Lord** [comment]
thank you!!
