### ISSUE TITLE
[Feature] forever player

### ISSUE THREAD

**Issue by Lead-Lord** [derfurkan/OfflinePlayers#8]
Could you please add a feature that keeps the clone even after rebooting the server?

I think this is a great fit for this plugin

**Comment by derfurkan** [comment]
This is a change that will most likely not happen since this task is not easily done in 5 min and needs more effort which i dont have right now. Soon or Later ill put that in but this is not planned for now.

**Comment by Lead-Lord** [comment]
okay
I will pray that you can do it
can win
